version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: akashic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: akashic
      POSTGRES_PASSWORD: akashic_password
      POSTGRES_DB: akashic_intelligence
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akashic -d akashic_intelligence"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: akashic_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application (for development)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akashic_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://akashic:akashic_password@postgres:5432/akashic_intelligence
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups

volumes:
  postgres_data:
  redis_data: