version: '3.8'

services:
  # Application
  app:
    image: akashic-campaign-console:latest
    container_name: akashic_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # These should be set via environment variables or secrets
      # DATABASE_URL: ${DATABASE_URL}
      # REDIS_HOST: ${REDIS_HOST}
      # REDIS_PORT: ${REDIS_PORT}
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
      # NEXTAUTH_URL: ${NEXTAUTH_URL}
      # NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      # OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    networks:
      - akashic_network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: akashic_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - app
    networks:
      - akashic_network

networks:
  akashic_network:
    driver: bridge

volumes:
  nginx_cache: