# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]

[start]
cmd = "npm run prisma:migrate:deploy && npm run start"