# Nixpacks configuration for Railway

[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = [
  "npx prisma generate",
  "SKIP_ENV_VALIDATION=1 NODE_OPTIONS='--max-old-space-size=4096' npm run build"
]

[start]
cmd = "npm run prisma:migrate:deploy && npm run start"

[variables]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "1"
NODE_OPTIONS = "--max-old-space-size=4096"