[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[phases.install]
cmds = [
    "rm -rf node_modules .next .npm || true",
    "npm install --no-cache --prefer-offline"
]

[phases.build]
cmds = [
    "npm run prisma:generate",
    "npm run build"
]

[start]
cmd = "npm run start"

[variables]
NEXT_TELEMETRY_DISABLED = "1"
NPM_CONFIG_CACHE = "/tmp/.npm"
NODE_OPTIONS = "--max-old-space-size=2048"