[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "echo 'Starting build process...'",
  "echo 'Node version:' && node --version",
  "echo 'NPM version:' && npm --version",
  "export SKIP_ENV_VALIDATION=1",
  "export DATABASE_URL='postgresql://dummy:dummy@localhost:5432/dummy'",
  "export NEXTAUTH_SECRET='dummy-secret-for-build-only-not-for-production'",
  "export NEXTAUTH_URL='http://localhost:3000'",
  "echo 'Running Prisma generate...'",
  "npm run prisma:generate",
  "echo 'Running Next.js build...'",
  "npm run build"
]

[start]
cmd = "npm run start"