[build]
builder = "nixpacks"
buildCommand = "npm run prisma:generate && npm run build"

[deploy]
startCommand = "npm run prisma:migrate:deploy && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10