[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules .next .npm && npm install --no-cache --prefer-offline && npm run prisma:generate && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health-simple"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3