// Re-export all onboarding components
export { default as OnboardingProgress } from './OnboardingProgress'
export { default as PersonalInfoStep } from './PersonalInfoStep'
export { default as PoliticalBackgroundStep } from './PoliticalBackgroundStep'
export { default as ProfessionalBackgroundStep } from './ProfessionalBackgroundStep'
export { default as CampaignDetailsStep } from './CampaignDetailsStep'
export { default as PolicyPositionsStep } from './PolicyPositionsStep'
export { default as CommunityInvolvementStep } from './CommunityInvolvementStep'
export { default as CommunicationStyleStep } from './CommunicationStyleStep'
export { default as OppositionResearchStep } from './OppositionResearchStep'
export { default as ReviewStep } from './ReviewStep'